#!/bin/bash

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF=$(git rev-parse --short HEAD)
CODE_VERSION=$(cat VERSION)

docker build \
  --build-arg BUILD_DATE="$BUILD_DATE"\
  --build-arg VCS_REF="$VCS_REF"\
  --build-arg VERSION="$CODE_VERSION"\
  -t "$IMAGE_NAME" .